### ISSUE TITLE
evaluate failed

### ISSUE THREAD

**Issue by huashijiacuo** [jeffsvajlenko/BigCloneEval#4]
## $./evaluateTool -t 1 -o nicad.report
 
There is some error with the database.  Try a new copy of the database, or report the error:
org.h2.jdbc.JdbcSQLException: Table "FUNCTIONALITIES" not found; SQL statement:
select id from functionalities [42102-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.readTableOrView(Parser.java:5213)
	at org.h2.command.Parser.readTableFilter(Parser.java:1220)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1859)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1968)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1853)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1674)
	at org.h2.command.Parser.parseSelect(Parser.java:1662)
	at org.h2.command.Parser.parsePrepared(Parser.java:434)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at com.jolbox.bonecp.StatementHandle.executeQuery(StatementHandle.java:464)
	at database.Functionalities.getFunctionalityIds(Functionalities.java:17)
	at evaluate.ToolEvaluator.<init>(ToolEvaluator.java:2480)
	at tasks.EvaluateTool.main(EvaluateTool.java:412)

**Comment by jeffsvajlenko** [comment]
This occurs when bigclonebenchdb/ is missing the bigclonebench database file (separate download link due to size, please see readme).

I will update to have program provide warning.  Seems h2 default is to initialize a new empty database.

**Comment by jeffsvajlenko** [comment]
Fix now in master.
